#!/usr/bin/env ruby
require_relative 'parse'
require_relative 'teach'
require_relative 'color'

begin
	raise 'CSV file path required' if ARGV.count == 0
	raise 'too many arguments' if ARGV.count != 1

	filepath = ARGV[0]

	teach_with_standardized parse_csv(filepath)

rescue Exception => e
	if e.message.empty?
		puts 'Exiting!'.red
	else
		puts "Error: #{e.message}".red
	end
end